name: Node.js Test and Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.6.0
      uses: actions/setup-node@v1
      with:
        node-version: 14.6.0
    - run: npm install
    - run: npm test
    - run: npm run eslint
